/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    dogs: Dog;
    litters: Litter;
    puppies: Puppy;
    applications: Application;
    'contact-messages': ContactMessage;
    testimonials: Testimonial;
    faqs: Faq;
    pages: Page;
    deposits: Deposit;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    dogs: DogsSelect<false> | DogsSelect<true>;
    litters: LittersSelect<false> | LittersSelect<true>;
    puppies: PuppiesSelect<false> | PuppiesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    deposits: DepositsSelect<false> | DepositsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Controls what this user can do in the dashboard.
   */
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos and images. Provide descriptive alt text for accessibility & SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional caption shown in galleries.
   */
  caption?: string | null;
  /**
   * Optional photographer credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * PDF documents such as the contract and health guarantee.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  category?: ('contract' | 'health-guarantee' | 'info-packet' | 'other') | null;
  /**
   * If on, the document can be linked publicly. If off, it is shared on request only.
   */
  public?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Parent and retired dogs in the breeding program.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs".
 */
export interface Dog {
  id: number;
  /**
   * Everyday name, e.g. "Daisy".
   */
  callName: string;
  /**
   * Full registered name, if applicable. (TODO: confirm)
   */
  registeredName?: string | null;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  role: 'sire' | 'dam' | 'retired';
  sex: 'male' | 'female';
  dateOfBirth?: string | null;
  /**
   * e.g. "Light cream".
   */
  color?: string | null;
  /**
   * e.g. "62 lbs".
   */
  weight?: string | null;
  /**
   * Temperament and personality notes.
   */
  temperament?: string | null;
  pedigreeNotes?: string | null;
  /**
   * Add only tests that have actually been completed. Do not list a result that has not been confirmed.
   */
  healthTesting?:
    | {
        /**
         * e.g. "OFA Hips".
         */
        test: string;
        /**
         * e.g. "Good".
         */
        result?: string | null;
        /**
         * Optional public link to the certificate (OFA, Embark, etc.).
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional, comma-separated.
   */
  titles?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Main profile photo.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Show on the public website.
   */
  published?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and site defaults.
   */
  seo?: {
    /**
     * Recommended ~50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended ~120–160 characters. Avoid keyword stuffing.
     */
    description?: string | null;
    /**
     * Social share image. ~1200×630.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Planned, current, and past litters.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litters".
 */
export interface Litter {
  id: number;
  /**
   * e.g. "Daisy × Cooper — Spring 2026".
   */
  name: string;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  sire?: (number | null) | Dog;
  dam?: (number | null) | Dog;
  status: 'planned' | 'expecting' | 'born' | 'available' | 'reserved' | 'placed';
  waitlistOpen?: boolean | null;
  expectedDate?: string | null;
  goHomeDate?: string | null;
  /**
   * Notes about the pairing and what you hope for in this litter.
   */
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Show on the public website.
   */
  published?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and site defaults.
   */
  seo?: {
    /**
     * Recommended ~50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended ~120–160 characters. Avoid keyword stuffing.
     */
    description?: string | null;
    /**
     * Social share image. ~1200×630.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual puppies. Deposits are never taken without breeder approval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puppies".
 */
export interface Puppy {
  id: number;
  /**
   * Name or collar color, e.g. "Green Collar".
   */
  name: string;
  /**
   * Used as the colored marker on puppy cards.
   */
  collarColor?: string | null;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  litter: number | Litter;
  sex: 'male' | 'female';
  status: 'available' | 'reserved' | 'under-evaluation' | 'waitlist-only' | 'placed';
  dateOfBirth?: string | null;
  goHomeDate?: string | null;
  /**
   * e.g. "Light cream".
   */
  color?: string | null;
  /**
   * Temperament and personality notes shown publicly.
   */
  notes?: string | null;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  /**
   * Show on the public website.
   */
  published?: boolean | null;
  /**
   * Safety gate. Even when on, deposits are only sent to applicants you have approved. This never creates a public "buy now" button.
   */
  allowDeposit?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Puppy applications. Internal notes and status are never shown publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  applicantName: string;
  email: string;
  phone: string;
  cityState: string;
  householdMembers: string;
  children?: string | null;
  otherPets?: string | null;
  housingType: 'house' | 'townhouse' | 'apartment' | 'farm' | 'other';
  yardFence?: ('fenced' | 'unfenced' | 'none') | null;
  workSchedule: string;
  priorExperience: string;
  vetReference?: string | null;
  activityLevel: string;
  trainingPlan: string;
  whyBreed: string;
  desiredTiming: string;
  sexPreference?: ('either' | 'male' | 'female') | null;
  /**
   * Optional — set if the application is about a specific puppy.
   */
  puppy?: (number | null) | Puppy;
  agreement: boolean;
  contactConsent: boolean;
  status: 'new' | 'needs-follow-up' | 'approved' | 'deposit-sent' | 'reserved' | 'waitlisted' | 'declined';
  /**
   * Private. Never displayed publicly.
   */
  adminNotes?: string | null;
  /**
   * Deposit links sent for this applicant.
   */
  linkedApplication?: (number | Deposit)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stripe deposit links for approved applicants only. Never a public purchase.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposits".
 */
export interface Deposit {
  id: number;
  /**
   * Internal label, e.g. "Deposit — Smith family — Green Collar".
   */
  label: string;
  /**
   * Approved application this deposit is for.
   */
  application: number | Application;
  puppy?: (number | null) | Puppy;
  /**
   * Deposit amount in USD.
   */
  amount: number;
  status?: ('draft' | 'sent' | 'paid' | 'refunded' | 'cancelled') | null;
  /**
   * Generated automatically from Stripe when configured. Copy and send to the approved applicant.
   */
  paymentUrl?: string | null;
  stripeId?: string | null;
  /**
   * Internal notes.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages from the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject?: string | null;
  message: string;
  /**
   * Mark when you have replied.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner testimonials. Only add real, received testimonials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  ownerName: string;
  dogName?: string | null;
  /**
   * e.g. "Richmond, VA".
   */
  location?: string | null;
  date?: string | null;
  /**
   * Optional photo.
   */
  photo?: (number | null) | Media;
  /**
   * Show on the public website.
   */
  published?: boolean | null;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'pricing' | 'waitlist' | 'registration' | 'health' | 'pickup' | 'care') | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editable content pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Optional intro shown under the page title.
   */
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Main page content.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show on the public website.
   */
  published?: boolean | null;
  /**
   * Optional. Leave blank to use the page title and site defaults.
   */
  seo?: {
    /**
     * Recommended ~50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended ~120–160 characters. Avoid keyword stuffing.
     */
    description?: string | null;
    /**
     * Social share image. ~1200×630.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'dogs';
        value: number | Dog;
      } | null)
    | ({
        relationTo: 'litters';
        value: number | Litter;
      } | null)
    | ({
        relationTo: 'puppies';
        value: number | Puppy;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'deposits';
        value: number | Deposit;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  public?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dogs_select".
 */
export interface DogsSelect<T extends boolean = true> {
  callName?: T;
  registeredName?: T;
  slug?: T;
  role?: T;
  sex?: T;
  dateOfBirth?: T;
  color?: T;
  weight?: T;
  temperament?: T;
  pedigreeNotes?: T;
  healthTesting?:
    | T
    | {
        test?: T;
        result?: T;
        link?: T;
        id?: T;
      };
  titles?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featuredImage?: T;
  published?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "litters_select".
 */
export interface LittersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sire?: T;
  dam?: T;
  status?: T;
  waitlistOpen?: T;
  expectedDate?: T;
  goHomeDate?: T;
  description?: T;
  coverImage?: T;
  published?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puppies_select".
 */
export interface PuppiesSelect<T extends boolean = true> {
  name?: T;
  collarColor?: T;
  slug?: T;
  litter?: T;
  sex?: T;
  status?: T;
  dateOfBirth?: T;
  goHomeDate?: T;
  color?: T;
  notes?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featuredImage?: T;
  published?: T;
  allowDeposit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  applicantName?: T;
  email?: T;
  phone?: T;
  cityState?: T;
  householdMembers?: T;
  children?: T;
  otherPets?: T;
  housingType?: T;
  yardFence?: T;
  workSchedule?: T;
  priorExperience?: T;
  vetReference?: T;
  activityLevel?: T;
  trainingPlan?: T;
  whyBreed?: T;
  desiredTiming?: T;
  sexPreference?: T;
  puppy?: T;
  agreement?: T;
  contactConsent?: T;
  status?: T;
  adminNotes?: T;
  linkedApplication?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  ownerName?: T;
  dogName?: T;
  location?: T;
  date?: T;
  photo?: T;
  published?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  heroImage?: T;
  body?: T;
  published?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deposits_select".
 */
export interface DepositsSelect<T extends boolean = true> {
  label?: T;
  application?: T;
  puppy?: T;
  amount?: T;
  status?: T;
  paymentUrl?: T;
  stripeId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, contact, trust badges, social links, and SEO defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  tagline?: string | null;
  /**
   * Breeder name shown publicly.
   */
  breederName?: string | null;
  /**
   * Show the breeder’s name publicly.
   */
  showBreederName?: boolean | null;
  /**
   * Optional. Falls back to a text wordmark.
   */
  logo?: (number | null) | Media;
  /**
   * Public email. Leave blank to use the contact form only.
   */
  email?: string | null;
  /**
   * Public phone. Leave blank to hide.
   */
  phone?: string | null;
  /**
   * Never expose a private street address unless you choose “Show full address”.
   */
  addressVisibility?: ('hidden' | 'generalized' | 'full') | null;
  city?: string | null;
  state?: string | null;
  /**
   * Only shown publicly if visibility is “Show full address”.
   */
  streetAddress?: string | null;
  postalCode?: string | null;
  /**
   * General area you serve (for SEO and the contact page).
   */
  serviceArea?: string | null;
  badgeAkc?: boolean | null;
  badgeOfa?: boolean | null;
  badgeEmbark?: boolean | null;
  badgeVetChecked?: boolean | null;
  badgeFamilyRaised?: boolean | null;
  facebook?: string | null;
  instagram?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  /**
   * Fallback page title.
   */
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  tagline?: T;
  breederName?: T;
  showBreederName?: T;
  logo?: T;
  email?: T;
  phone?: T;
  addressVisibility?: T;
  city?: T;
  state?: T;
  streetAddress?: T;
  postalCode?: T;
  serviceArea?: T;
  badgeAkc?: T;
  badgeOfa?: T;
  badgeEmbark?: T;
  badgeVetChecked?: T;
  badgeFamilyRaised?: T;
  facebook?: T;
  instagram?: T;
  youtube?: T;
  tiktok?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}